version: '2'

services: 
  arduino: 
      image: cristidragomir97/arduino-block:arm64
      privileged: true
      restart: always
      environment:
        - REPO="https://github.com/cristidragomir97/motorhead"
        - SKETCH_FOLDER=/firmware
        - AVRDUDE_CPU=atmega328p
        - MONITOR_BAUD=9600
        - SERIAL_PORT=/dev/ttyAMA0
        - ARDUINO_FQBN=arduino:avr:pro:cpu=8MHzatmega328
        - RESET_PIN=18
      labels:
        io.balena.features.dbus: '1'
        
  motorhead:
    privileged: true
    build: .
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.balena-socket: 1
    devices:
      - "/dev:/dev"

